apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: du0nxd98t-python
  janus-idp.io/tekton: du0nxd98t-python
  backstage.io/kubernetes-id: du0nxd98t-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: du0nxd98t-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
